export const ADD_PLANNED_MEAL_SUCCESS = 'ADD_PLANNED_MEAL_SUCCESS';
export const ADD_PLANNED_MEAL_ERROR = 'ADD_PLANNED_MEAL_ERROR';
export const ADD_PLANNED_MEAL_LOADING = 'ADD_PLANNED_MEAL_LOADING';
export const GET_PLANNED_MEALS_SUCCESS = 'GET_PLANNED_MEALS_SUCCESS';
export const GET_PLANNED_MEALS_ERROR = 'GET_PLANNED_MEALS_ERROR';